### ISSUE TITLE
hpos-admin-api: Cannot edit config due to USB permissions issue

### ISSUE THREAD

**Issue by timotree3** [Holo-Host/holo-nixpkgs#1068]
Host Console makes a `PUT /api/v1/config` call in order to persist a `deviceName` key on the HoloPort ([this line](https://github.com/Holo-Host/host-console-ui/blob/2c960bcdda8fcd034d984b581d70abf23ffc134f/src/interfaces/HposInterface.js#L148)). This call errors with status 500, and the following is logged by hpos-admin-api: 

```
Jan 19 02:39:01 hpos hpos-admin-api[1320]: [2022-01-19 02:39:01,942] ERROR in app: Exception on /config [PUT]
Jan 19 02:39:01 hpos hpos-admin-api[1320]: Traceback (most recent call last):
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/iy4a3vdgjrwwd3ff2j5wlbw532dcffir-python3-3.8.5-env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi>
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     response = self.full_dispatch_request()
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/iy4a3vdgjrwwd3ff2j5wlbw532dcffir-python3-3.8.5-env/lib/python3.8/site-packages/flask/app.py", line 1952, in full>
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     rv = self.handle_user_exception(e)
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/iy4a3vdgjrwwd3ff2j5wlbw532dcffir-python3-3.8.5-env/lib/python3.8/site-packages/flask/app.py", line 1821, in hand>
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     reraise(exc_type, exc_value, tb)
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/iy4a3vdgjrwwd3ff2j5wlbw532dcffir-python3-3.8.5-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in re>
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     raise value
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/iy4a3vdgjrwwd3ff2j5wlbw532dcffir-python3-3.8.5-env/lib/python3.8/site-packages/flask/app.py", line 1950, in full>
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     rv = self.dispatch_request()
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/iy4a3vdgjrwwd3ff2j5wlbw532dcffir-python3-3.8.5-env/lib/python3.8/site-packages/flask/app.py", line 1936, in disp>
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     return self.view_functions[rule.endpoint](**req.view_args)
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/arbjb48chy94x8r2i8bdff6y8jdr0kcd-hpos-admin-api.py", line 78, in put_settings
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     replace_file_contents(get_state_path(), state_json)
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/arbjb48chy94x8r2i8bdff6y8jdr0kcd-hpos-admin-api.py", line 57, in replace_file_contents
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     fd, tmp_path = mkstemp(dir=os.path.dirname(path))
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/tempfile.py", line 332, in mkstemp
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
Jan 19 02:39:01 hpos hpos-admin-api[1320]:   File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
Jan 19 02:39:01 hpos hpos-admin-api[1320]:     fd = _os.open(file, flags, 0o600)
Jan 19 02:39:01 hpos hpos-admin-api[1320]: PermissionError: [Errno 13] Permission denied: '/media/sdc1-usb-USB_Flash_Disk-0/tmpud8y5rnq'
```

I think we already knew about this bug. (This is the USB permissions issue that @peeech struggled with before.)

I looked into the permissions a bit. Here is what I found
```
[root@hpos:~]# ls -ld /media/sdc1-usb-USB_Flash_Disk-0/
drwxr-xr-x 3 root root 8192 Jan  1  1970 /media/sdc1-usb-USB_Flash_Disk-0/

[root@hpos:~]# ls -l /media/sdc1-usb-USB_Flash_Disk-0/hp-primary-2kse8.json 
-rw-r--r-- 1 root root 549 Jan 14 18:35 /media/sdc1-usb-USB_Flash_Disk-0/hp-primary-2kse8.json

[root@hpos:~]# ps faux | grep hpos-admin-api
root     16102  0.0  0.0 217956  2260 pts/0    S+   22:41   0:00          \_ grep hpos-admin-api
admin-a+  1320  0.0  0.2 253752 34624 ?        Ss   Jan18   0:00 /nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/bin/python3 /nix/store/arbjb48chy94x8r2i8bdff6y8jdr0kcd-hpos-admin-api.py
```

It looks like the USB drive is only writable by `root`, but hpos-admin-api runs under an `admin-api` user. (It just says `admin-a+`, but I'm assuming it's truncating `admin-api`).

One possible solution would be to have some process that runs as root and changes the permissions/group ownership of the mounted USB so that it's accessible to `admin-api`. Not sure whether this would cause harmful side effects when trying to use the USB on other devices later.

**Comment by alastairong** [comment]
@peeech 

Cole posted a permissions fix for `configure-holochain` [here](https://github.com/Holo-Host/holo-nixpkgs/pull/1032/files/96ab89f5c9a798ad296b0d055e9d7b80e0ddad97#r779830153) and I wonder whether it's the same issue for admin-api.
