### ISSUE TITLE
get-hosted-happs endpoint inconsistent

### ISSUE THREAD

**Issue by zo-el** [Holo-Host/holo-nixpkgs#578]
Note: holo-envoy also connects to port 42222 to call servicelogger.

```
[root@hpos:~]# hpos-admin-client --url=http://localhost get-hosted-happs
Traceback (most recent call last):
  File "/nix/store/89d24kmwdm93rvxvh94bj4slg9kzgs5b-hpos-admin-client.py", line 93, in <module>
    cli(obj={})
  File "/nix/store/dbz61c7nrxhqkambrqiz2ciran91gxln-python3-3.7.5-env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/dbz61c7nrxhqkambrqiz2ciran91gxln-python3-3.7.5-env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/dbz61c7nrxhqkambrqiz2ciran91gxln-python3-3.7.5-env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/dbz61c7nrxhqkambrqiz2ciran91gxln-python3-3.7.5-env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/dbz61c7nrxhqkambrqiz2ciran91gxln-python3-3.7.5-env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/dbz61c7nrxhqkambrqiz2ciran91gxln-python3-3.7.5-env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/89d24kmwdm93rvxvh94bj4slg9kzgs5b-hpos-admin-client.py", line 82, in get_hosted_happs
    print(request(ctx, 'GET', '/hosted_happs').json())
  File "/nix/store/dbz61c7nrxhqkambrqiz2ciran91gxln-python3-3.7.5-env/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by alastairong** [comment]
Closing as this end point is deprecated
