### ISSUE TITLE
hpos-holochain-api /hosted-happs endpoint has a non-breaking error

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-nixpkgs#727]
```
[root@hpos:~]# hpos-holochain-client --url=http://localhost/holochain-api/ hosted-happs
[{'id': 'uhCkkkKftUYRw7zHpGwgUBIaWqgPsuWRdURZjjkdb6CR_oaCBz3jw', 'name': 'Elemental Chat', 'enabled': False, 'error': {'source': 'uhCkkkKftUYRw7zHpGwgUBIaWqgPsuWRdURZjjkdb6CR_oaCBz3jw::servicelogger', 'message': "Couldn't find Holo Hosting App with id uhCkkkKftUYRw7zHpGwgUBIaWqgPsuWRdURZjjkdb6CR_oaCBz3jw::servicelogger", 'stack': "Error: Couldn't find Holo Hosting App with id uhCkkkKftUYRw7zHpGwgUBIaWqgPsuWRdURZjjkdb6CR_oaCBz3jw::servicelogger\n    at callZome (/nix/store/mgww7g0i3hwqzinw5yf8mbp3arvw4khb-hpos-holochain-api/libexec/hpos-holochain-api/deps/hpos-holochain-api/src/api.js:126:11)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async getPresentedHapps (/nix/store/mgww7g0i3hwqzinw5yf8mbp3arvw4khb-hpos-holochain-api/libexec/hpos-holochain-api/deps/hpos-holochain-api/src/index.js:27:18)\n    at async /nix/store/mgww7g0i3hwqzinw5yf8mbp3arvw4khb-hpos-holochain-api/libexec/hpos-holochain-api/deps/hpos-holochain-api/src/index.js:68:28"}}]
```

**Comment by zo-el** [comment]
@alastairong this is not a bug. This was a UI API choice by lisa and robbie in this https://github.com/Holo-Host/holo-nixpkgs/pull/708

So when a happ is not activated it will return an error instead of returning the stats.

**Comment by alastairong** [comment]
Ok. In this case it is not installed. Is that expected?
